<?php

/**
 * Created by PhpStorm.
 * User: Georgi
 * Date: 2/22/2016
 * Time: 3:34 PM
 */

namespace app\modules\admin\components;

use yii\base\Widget;
use app\models\User;

class UsersWidget extends Widget {
    public $registeredUsers;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->registeredUsers = User::find()->count();
    }

    public function run()
    {
        return $this->render('usersWidget/index', [
            'registeredUsers' => $this->registeredUsers
        ]);
    }
}