<?php
/**
 * Created by PhpStorm.
 * User: Georgi
 * Date: 2/16/2016
 * Time: 11:13 PM
 */

namespace app\modules\admin\controllers;


class EventController extends BaseAdminController {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->addRoles(['moderator']);
    }

    public function actionIndex(){
        return $this->render('index');
    }
}