<?php
/**
 * Created by PhpStorm.
 * User: Georgi
 * Date: 2/21/2016
 * Time: 1:45 PM
 */

namespace app\components;

use app\models\Setting;

class View extends \yii\web\View{

    public $settings;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->settings = Setting::getAll();
    }
}